#!/usr/bin/env bash
# Phil Espinoza, Aug 29, 2016 - present
# terminal
alias back='cd -'
alias c='clear'
alias cc='clear clear'
alias cdup='cd ..'
alias ls='ls -a'
alias na='nano ~/.bash_aliases'
alias rm='rm -i'
alias sa='source ~/.bash_aliases'
alias watch='watch --color git -c color.status=always status -sb'
# cli tools
alias emacs='/usr/local/Cellar/emacs/24.5/Emacs.app/Contents/MacOS/Emacs -nw'
alias e='emacs'
alias epwd='e $(pwd)'
alias py='python'
alias flaks='flask'
alias ql='qlmanage -p "$@" &> /dev/null'
# git
alias ga='git add'
alias gal='ga *'
alias gb='git branch --all'
alias gcl='gco -- .'
alias gcm='git commit -m'
alias gco='git checkout'
alias gcob='gco -b'
alias gcom='gco master'
alias gd='git diff'
alias gf='git fetch --all -p'
alias gs='git status'
alias gl='git log'
alias gm='git merge'
alias gmm='gm master'
alias gpl='git pull'
alias gps='git push'
# ruby and rails
alias rb='ruby'
alias bins='./bin/server'
alias bi='bundle install && say Bundle Install Complete'
alias ni='npm install && say NPM Install Complete'
alias brs='bundle exec rails server'
alias brc='bundle exec rails console'
alias brt='bin/rake test'
alias rdb='rake db:test:prepare && say Rake DB Test Prepare Done'
alias rt='rake test && say Rake Test Done'
alias rmigrate='rake db:migrate && say Rake DB Migrate Done'
alias brcd='bin/rake db:create RAILS_ENV=development'
alias brmd='bin/rake db:migrate RAILS_ENV=development'
alias brsd='bin/rake db:seed RAILS_ENV=development'
alias brmrd='bin/rake db:migrate:reset RAILS_ENV=development'
alias brct='bin/rake db:create RAILS_ENV=test'
alias brmt='bin/rake db:migrate RAILS_ENV=test'
alias brst='bin/rake db:seed RAILS_ENV=test'
alias brmrt='bin/rake db:migrate:reset RAILS_ENV=test'
alias dbr='brmrt && say Test DB Reset Done;brmrd && say Dev DB Reset Done;brsd && say Dev DB Seeding Done'
# ruby and rails tools
alias bg='bin/guard'
alias fs='foreman start'
alias fss='foreman start server'
